//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolioProjectNight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio
    {
        public int PortfolioID { get; set; }
        public string PortfolioTitle { get; set; }
        public string PortfolioSubTitle { get; set; }
        public string PortfolioImageUrl { get; set; }
    }
}
